version: "3.9"
services:
  testpostgres:
    build:
      context: ./3-bd
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./3-bd:/bd
