[package]
name = "delimitador"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.7"
roots = "0.0.8"
statrs = "0.17.1"
